#!/bin/bash

xrdb --merge /home/sam/.Xresources
xrandr --output HDMI-2 --off --output HDMI-1 --off --output DP-1 --off --output eDP-1 --primary --mode 1920x1200 --pos 0x0 --rotate normal --output DP-2 --off
bash /home/sam/.dwm/autostart.sh &

sleep 1

exec dwm
